### ISSUE TITLE
03-scatter-gather run bug....

### ISSUE THREAD

**Issue by jiapei100** [jbornschein/mpi4py-examples#12]
```console
pi@pi01:~/Downloads/mpi4py-examples $ mpirun --hostfile ~/hostfile 03-scatter-gather 
------------------------------------------------------------------------------
  Running on 16 cores
 ------------------------------------------------------------------------------
 After Scatter:
 [0] [0. 1. 2. 3.]
[1] [4. 5. 6. 7.]
[pi01][[24145,1],0][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[24145,1],3]
[2] [ 8.  9. 10. 11.]
[pi03][[24145,1],8][btl_tcp_endpoint.c:626:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[24145,1],10]
```

**Comment by jbornschein** [comment]
I have never seen this message before.

I suspect you are using OpenMPI? A quick google search suggests it sometimes pops up when running on multiple cluster nodes that have somewhat complex network configurations. E.g. (virtual) multiple network interfaces. Or for example dunning docker containers that use corresponding virtual network interfaces.

Could this be the case for you?

**Comment by jiapei100** [comment]
My bad... I now specify parameter `--mca btl_tcp_if_include "192.168.1.251/24,192.168.1.249/24,192.168.1.247/24"`, and example **03-scatter-gather** runs.
