### ISSUE TITLE
05-pseudo-whitening line 18: ModuleNotFoundError: No module named 'bernstein'

### ISSUE THREAD

**Issue by jiapei100** [jbornschein/mpi4py-examples#13]
```console
ModuleNotFoundError: No module named 'bernstein'
```
Where can I find `bernstein` package?

Cheers

**Comment by jbornschein** [comment]
Hi, 

Oh, that module should not been imported at all -- and its not used in any of the examples here. 

You can safely remove that line.


I will update the repository accordingly ASAP.

Thanks for pointing it out!


Update: Closed by c0f5fa18bab612fb5afbd9a5bdbc47521d6c6dd6
