### ISSUE TITLE
How to use mpi4py on a cluster

### ISSUE THREAD

**Issue by xysoul** [jbornschein/mpi4py-examples#5]
Hello, thanks for sharing such good examples which have much learning value.
I have a question on when I want to run the .py files of mpi4py, is there any configuration or setting I should do on the cluster?
Looking forward to your reply. Thanks so much!

**Comment by jbornschein** [comment]
Hi, 

that very much depends on the cluster you want to use: The distribution; the scheduling software and the general setup. The README contains a typical example for the Torque scheduling system, but there are many others; and the commands you have to run vary between them and between different configurations.

You should talk to one of your administrators or to an experienced uses of your cluster.

**Comment by xysoul** [comment]
Hi, 
thanks for your advice.
